name = "Yahtzee"
uuid = "05495954-d9f0-4bff-910a-baafe1f339c0"
authors = ["P0kenzo", "SergeSuuu", "yannisp855"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
